Delete unused file and fix clang warning
Got clang warning from GitHub Workflow:

     CC		 src/gwbot/config.o
     CC		 src/gwbot/event_handler.o
     CC		 src/gwbot/event_logger.o
  In file included from /home/runner/work/GNUWeebBot/GNUWeebBot/src/gwbot/event_logger.c:11:
  /home/runner/work/GNUWeebBot/GNUWeebBot/src/gwbot/include/gwbot/gwchan.h:17:5: error: 'QWE' is not defined, evaluates to 0 [-Werror,-Wundef]
  #if QWE
      ^
  1 error generated.
  make: *** [/home/runner/work/GNUWeebBot/GNUWeebBot/src/gwbot/Makefile:34: /home/runner/work/GNUWeebBot/GNUWeebBot/src/gwbot/event_logger.o] Error 1
  make: *** Waiting for unfinished jobs....
  Error: Process completed with exit code 2.

Signed-off-by: Ammar Faizi <ammarfaizi2@gmail.com>